version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: alfsns/rest_pract_1
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_rest
      - PG_USER=postgres
      - PG_PASSWORD=sns2018
      - PG_HOST=node_db
    depends_on:
      - node_db
    

  node_db:
    container_name: node_db
    image: postgres:14.9
    environment:
      - POSTGRES_DB=node_rest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sns2018
    ports:
      - "5432:5432"
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: